services:
  - type: web
    name: beautifulstore-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: singapore

build:
  pythonVersion: 3.10.13
