services:
  - type: web
    name: beautifulstore-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: singapore

buildCommand: "./build.sh"
envVars:
  - key: PYTHON_VERSION
    value: 3.11.9

