services:
  - type: web
    name: beautifulstore-app
    env: python
    buildCommand: "./build.sh"  # ← ✅ 이걸 유지
    startCommand: "gunicorn app:app"
    plan: free
    region: singapore
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SUPABASE_URL
        value: your_supabase_url
      - key: SUPABASE_KEY
        value: your_supabase_key
